name    'saz-tftp'
version '0.0.1'
source 'UNKNOWN'
author 'saz'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'Manage tftp server and client'
project_page 'https://github.com/saz/puppet-tftp'
